name: Contribute to the CEFI resource list
description: The form is designed for user to easily contribute to the CEFI resource
  list that will be used in the CEFI resource search portal
title: '[Add new CEFI resource]: '
assignees:
- chiaweh2
body:
- type: markdown
  attributes:
    value: Thanks for taking the time to contribute to the CEFI resource list!
- type: input
  id: data-title
  attributes:
    label: What is the best title for the data/resource?
    description: A title that best summarize the content.
    placeholder: Global Marine Heatwaves Forecast and Observation
  validations:
    required: true
- type: input
  id: data-url
  attributes:
    label: What is URL that links to data/resource?
    description: A complete URL that lead to the data/resource
    placeholder: https://psl.noaa.gov/marine-heatwaves/
  validations:
    required: true
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
- type: textarea
  id: data-why
  attributes:
    label: Tell us a bit about the data/resource!
    description: Why you think this data worth to be put into the CEFI resource list?
    placeholder: A short sentence or paragraph on why you think the data/resource
      is important.
  validations:
    required: false
- type: textarea
  id: data-figure
  attributes:
    label: Provide a representative figure that relates to the data/resource!
    description: What figure best summarize the data/resource?
    placeholder: A short name for the figure (aspect ratio of 16:9 is prefered) and
      please attach the figure here.
  validations:
    required: false
- type: markdown
  attributes:
    value: '# CEFI data/resource categories'
- type: markdown
  attributes:
    value: '---'
- type: markdown
  attributes:
    value: Below are dropdowns with multiple choices available in each dropdown.
- type: markdown
  attributes:
    value: Please select all options that the CEFI data/resource provides (if nothing
      fits, please select "Any").
- type: dropdown
  id: cdata
  attributes:
    label: Dataset
    multiple: true
    options:
    - 0-Any
    - 1-ICOADS
    - 2-CMIP5
    - 3-CMIP6
    - 4-NOAA GODAS
    - 5-CMIP3
    - 6-TAO Array
    - 7-AMIPS
    - 8-ARGO Floats
    - 9-NOAA ERSST V5
    - 10-North American Multi-Model Ensemble (NMME)
    - 11-Alaska Climate Integrated Modeling (ACLIM data)
    - 12-NOAA OI SST
    - 13-Coupled Models
    - 14-GLORYS
  validations:
    required: true
- type: dropdown
  id: ctime
  attributes:
    label: Time Scale
    multiple: true
    options:
    - 0-Any
    - 1-Sub Daily
    - 2-Daily
    - 3-Pentad
    - 4-Weekly
    - 5-Monthly
    - 6-Seasonal
    - 7-Annual
    - 8-Decadal
    - 9-Century
  validations:
    required: true
- type: dropdown
  id: cvar
  attributes:
    label: Variables
    multiple: true
    options:
    - 0-Any
    - 1-Sea Surface Temperature (SST)
    - 2-Sea Level Height
    - 3-Sea Level Pressure (SLP)
    - 4-Surface Pressure
    - 5-Currents
    - 6-Salinity
    - 7-Heat Fluxes
    - 8-Tidal
    - 9-Chlorphyll
    - 10-Mixed Layer Depth
    - 11-Waves
    - 12-Precipitation
    - 13-Sea-Ice
    - 14-Fish
    - 15-Wind Stress
    - 16-Evaporation
    - 17-Potential Temperature
    - 18-OLR
    - 19-Upwelling Indices
    - 20-Surface Temperature
    - 21-20C Isotherm
    - 22-Surface Winds
    - 23-Kelp and Seagrasses
    - 24-Algal Blooms
    - 25-Carbon
    - 26-Bathymetry
    - 27-Zooplankton
    - 28-Phytoplankton
    - 29-Oxygen
    - 30-Nitrates
    - 31-Bottom Temperature
    - 32-Clouds
    - 33-Heat Content
    - 34-DNA
    - 35-Density
    - 36-Coral
    - 37-Sea Mammals
    - 38-Atmosphere Variables
    - 39-Ocean Surface Variables
    - 40-Subsurface Ocean Variables
    - 41-Chemical Variables
    - 42-Marine Animal Variables
    - 43-Fish
    - 44-Marine Plant Variables
  validations:
    required: true
- type: dropdown
  id: cproduct
  attributes:
    label: Product Types
    multiple: true
    options:
    - 0-Any
    - '1-Values: Current'
    - '2-Values: Historic'
    - 3-Reanalysis
    - 4-Gridded Analysis
    - 5-Interactive Plotting Pages
    - 6-Forecasts
    - 7-Stations
    - 8-Animations
    - 9-In-situ
    - 10-Remote Sensing
    - 11-Data Guides/Repositories
    - 12-Code Repository
    - 13-Index Time-series
    - 14-Image/Animation Repository
    - 15-Educational
    - 16-International Data Repositories
    - 17-Analysis Tools
    - 18-ERDDAP Installations
    - 19-Reports
  validations:
    required: true
- type: dropdown
  id: ctopics
  attributes:
    label: Topics
    multiple: true
    options:
    - 0-Any
    - 1-ENSO
    - 2-MJO
    - 3-AMOC
    - 4-PDO
    - 5-Sea Level
    - 6-Long term Change
    - 7-Long term Indices
    - 8-Extremes
    - 9-Marine Heatwaves
    - 10-Arctic
    - 11-Hurricanes
    - 12-Air-Sea Interaction
    - 13-Upwelling
    - 14-Coastal Processes
    - 15-Inundation
    - 16-Economics
    - 17-Gulf Stream
    - 18-Wind Energy
    - 19-Indicators
    - 20-Resiliency
    - 21-Algae Blooms
  validations:
    required: true
- type: dropdown
  id: cplatforms
  attributes:
    label: Observing Platforms
    multiple: true
    options:
    - 0-Any
    - 1-Buoy
    - 2-Platform
    - 3-Ship
    - 4-Airplane
    - 5-Satellite
    - 6-Floats
    - 7-CTDs
    - 8-Saildrone
    - 9-Drones
    - 10-Gliders
    - 11-Radar
    - 12-River Gauge
    - 13-Stations
    - 14-Surface Drifters
    - 15-Wave Gliders
  validations:
    required: true
- type: dropdown
  id: cregions
  attributes:
    label: Regions
    multiple: true
    options:
    - 0-Any
    - 1-Atlantic Ocean
    - 2-Pacific Ocean
    - 3-Indian Ocean
    - 4-Arctic Ocean
    - 5-Bering Sea
    - '6-US: Coastal'
    - 7-California
    - 8-Oregon
    - 9-Washington
    - 10-Maine
    - 11-Florida
    - '12-US: East Coast'
    - 13-LMEs
    - 14-Hawaii
    - 15-Global
    - 16-Northern Hemisphere
    - 17-Alaska
    - '18-US: West Coast'
    - 19-Louisiana
    - '20-US: CONUS'
    - 21-Pacific Islands
  validations:
    required: true
- type: dropdown
  id: corgs
  attributes:
    label: Organizations
    multiple: true
    options:
    - 0-Any
    - 1-NOAA PSL
    - 2-NOAA PMEL
    - 3-NOAA AOML
    - 4-NOAA NOS
    - 5-NOAA NESDIS
    - 6-NOAA NCEI
    - 7-NCAR/UCAR
    - 8-U Hawaii
    - '9-UCSD: University of California at San Diego'
    - 10-NASA
    - 11-NOAA IRI
    - '12-NOAA: Center for Operational Oceanographic Products and Services'
    - 13-NOAA Data
    - 14-NOAA Fisheries
    - '15-IOOS: Integrated Ocean Observing System'
    - 16-NOAA CPC
    - 17-NOAA Tides and Currents
    - 18-Other
    - 19-NOAA Integrated Ecosystem Assessment
    - 20-NOAA Coastwatch
    - 21-NOAA GFDL
    - 22-NOAA Exploration
    - 23-NOAA (Any)
    - '24-AOOS: Alaska Ocean Observing System'
  validations:
    required: true
