name: Generate README and ISSUE TEMPLATE workflow

on:
  pull_request:
  push:
     branches:
       - main
     paths:
       - 'generate_issue_template.py' 
       - '.github/ISSUE_TEMPLATE/header_file/add_cefi_resource_head.yml'
       - 'generate_readme.py'
       - 'data/cefi_list.json'
#  schedule:
#    - cron: "0 12 5 * *"

jobs:
  generate_readme_and_issue_temp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash

      - name: Generate the README and ISSUE TEMP from JSON source
        shell: bash -l {0}
        run: >
          python generate_readme.py
          && python generate_issue_template.py

      - name: Commit and push if it changed
        if: success() && github.ref == 'refs/heads/main'
        shell: bash -l {0}
        run: >
          git config user.name "GitHub Action"
          && git config user.email "actions@users.noreply.github.com"
          && git add -A
          && timestamp=$(date -u)
          && git commit -m "Update latest data: ${timestamp} from GH Action" || exit 0
          && git push
